spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_example?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: dev@2019

  redis:
    host: 10.166.15.x
    port: 6379
    database: 0
    password: xxx
    jedis:
      pool:
        max-active: 1000
        max-idle: 1000
        min-idle: 100
        max-wait: -1
